DROP TABLE IF EXISTS CENTROS_FORENSES CASCADE;
DROP TABLE IF EXISTS MUESTRAS_FORENSES CASCADE;
DROP TABLE IF EXISTS INFORMES_FORENSES CASCADE;

CREATE TABLE CENTROS_FORENSES(
    id_centro INTEGER,
    nombre VARCHAR (50),
    PAIS VARCHAR (100),
    NIVEL_SEGURIDAD INTEGER,
    AUTOR_EXAMEN VARCHAR(150),
    CONSTRAINT PK_CENTROS_FORENSES_id_centro PRIMARY KEY (id_centro),
    CONSTRAINT NN_CENTROS_FORENSES_nombre CHECK (nombre IS NOT NULL),
    CONSTRAINT NN_CENTROS_FORENSES_PAIS CHECK (PAIS IS NOT NULL),
    CONSTRAINT NN_CENTROS_FORENSES_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL)
);

CREATE TABLE MUESTRAS_FORENSES(
    id_muestra INTEGER,
    CODIGO_CASO INTEGER,
    TIPO_MUESTRA VARCHAR,
    FECHA_RECOGIDA DATE,
    ESTADO_CUSTODIA BOOLEAN DEFAULT FALSE,
    id_centro INTEGER,
    AUTOR_EXAMEN VARCHAR(150),
    CONSTRAINT PK_MUESTRAS_FORENSES_id_muestra PRIMARY KEY (id_muestra),
    CONSTRAINT UQ_MUESTRAS_FORENSES_CODIGO_CASO UNIQUE (CODIGO_CASO),
    CONSTRAINT NN_MUESTRAS_FORENSES_TIPO_MUESTRA CHECK (TIPO_MUESTRA IS NOT NULL),
    CONSTRAINT NN_MUESTRAS_FORENSES_CODIGO_CASO CHECK (CODIGO_CASO IS NOT NULL),
    CONSTRAINT NN_MUESTRAS_FORENSES_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL),
    CONSTRAINT fk_MUESTRAS_FORENSES FOREIGN KEY (id_centro) REFERENCES centros_forenses (id_centro)
);

CREATE TABLE INFORMES_FORENSES(
    id_informe INTEGER,
    ADN_POSITIVO BOOLEAN DEFAULT FALSE,
    NIVEL_RIESGO INTEGER,
    CONCLUSION VARCHAR (250),
    id_muestra INTEGER,
    AUTOR_EXAMEN VARCHAR (150),
    CONSTRAINT PK_INFORMES_FORENSES_id_informe PRIMARY KEY (id_informe),
    CONSTRAINT UQ_INFORMES_FORENSES_id_muestra UNIQUE (id_muestra),
    CONSTRAINT NN_INFORMES_FORENSES_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL),
    CONSTRAINT fk_INFORMES_FORENSES FOREIGN KEY (id_muestra) REFERENCES muestras_forenses (id_muestra)
);