DROP TABLE IF EXISTS CENTROS_FORENSES;
DROP TABLE IF EXISTS MUESTRAS_FORENSES;
DROP TABLE IF EXISTS INFORMES_FORENSES;
CREATE TABLE CENTROS_FORENSES(
    id_centro INTEGER,
    nombre VARCHAR (50),
    PAIS VARCHAR (100),
    NIVEL_SEGURIDAD INTEGER,
    AUTOR_EXAMEN VARCHAR(150),
    CONSTRAINT PK_CENTROS_FORENSES_id_centro PRIMARY KEY (id_centro),
    CONSTRAINT NN_CENTROS_FORENSES_nombre CHECK (nombre IS NOT NULL),
    CONSTRAINT NN_CENTROS_FORENSES_PAIS CHECK (PAIS IS NOT NULL),
    CONSTRAINT NN_CENTROS_FORENSES_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL)
);

CREATE TABLE MUESTRAS_FORENSES(
    id_muestra INTEGER,
    CODIGO_CASO INTEGER (50), --UNIQUE
    TIPO_MUESTRA VARCHAR,
    ESTADO_CUSTODIA BOOLEAN DEFAULT FALSE,
    fecha_lanzamiento DATE,
    id_centro INTEGER,
    AUTOR_EXAMEN VARCHAR(150),
    CONSTRAINT PK_MUESTRAS_FORENSES_id_muestra PRIMARY KEY (id_muestra),
    CONSTRAINT NN_MUESTRAS_FORENSES_nombre CHECK (nombre IS NOT NULL),
    CONSTRAINT NN_MUESTRAS_FORENSES_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL),
    CONSTRAINT FK_MUESTRAS_FORENSES_id_centro (id_centro) REFERENCES CENTROS_FORENSES(id_centro)
);

CREATE TABLE INFORMES_FORENSES(
    id_detalle INTEGER,
    velocidadMaxima INTEGER,
    combustible INTEGER,
    vidaUtil INTEGER,
    id_satelite INTEGER,
    AUTOR_EXAMEN VARCHAR (150),
    CONSTRAINT PK_INFORMES_FORENSES_id_detalle PRIMARY KEY (id_detalle),
    CONSTRAINT UQ_INFORMES_FORENSES_id_satelite UNIQUE (id_satelite),
    CONSTRAINT NN_INFORMES_FORENSES_AUTOR_EXAMEN CHECK (AUTOR_EXAMEN IS NOT NULL),
    CONSTRAINT FK_INFORMES_FORENSES_id_satelite (id_satelite) REFERENCES DETALLE_SATELITE(id_satelite)
);