INSERT INTO CENTROS_FORENSES VALUES (1,'nasai','japon','5','AINARA_GORRIA_DAM2');
INSERT INTO CENTROS_FORENSES VALUES (2,'Ferraz','espanya','3','AINARA_GORRIA_DAM2');
INSERT INTO CENTROS_FORENSES VALUES (3,'Kiev','rusia','9','AINARA_GORRIA_DAM2');
INSERT INTO CENTROS_FORENSES VALUES (4,'nasa','estados unidos','10','AINARA_GORRIA_DAM2');
INSERT INTO CENTROS_FORENSES VALUES (5,'cobre','venezuela','6','AINARA_GORRIA_DAM2');

INSERT INTO MUESTRAS_FORENSES VALUES (1,'056','viva','12-04-2005','TRUE','1','AINARA_GORRIA_DAM2');
INSERT INTO MUESTRAS_FORENSES VALUES (2,'123','muerta','13-06-2020','TRUE','3','AINARA_GORRIA_DAM2');
INSERT INTO MUESTRAS_FORENSES VALUES (3,'342','viva','30-08-2017','FALSE','2','AINARA_GORRIA_DAM2');
INSERT INTO MUESTRAS_FORENSES VALUES (4,'654','viva','26-07-2006','FALSE','4','AINARA_GORRIA_DAM2');
INSERT INTO MUESTRAS_FORENSES VALUES (5,'324','muerta','13-12-1996','TRUE','5','AINARA_GORRIA_DAM2');

INSERT INTO INFORMES_FORENSES VALUES (1,'TRUE','90','Se espera a tratar','1','AINARA_GORRIA_DAM2');
INSERT INTO INFORMES_FORENSES VALUES (2,'FALSE','54','Peligro de derrame','2','AINARA_GORRIA_DAM2');
INSERT INTO INFORMES_FORENSES VALUES (3,'TRUE','100','Peligro inminente','3','AINARA_GORRIA_DAM2');
INSERT INTO INFORMES_FORENSES VALUES (4,'FALSE','23','Riesgo de fuga','4','AINARA_GORRIA_DAM2');
INSERT INTO INFORMES_FORENSES VALUES (5,'TRUE','89','Posible virus antiguo','5','AINARA_GORRIA_DAM2');